#Trabajo Práctico Redes Neuronales
Participantes:
- Zoe Pérez Colman
- Bautista Czerniuk
- Benicio Pastorino

#_Introducción_
El objetivo de este trabajo es plantear una red neuronal con una capa de entrada con **N** neuronas y una capa de salida con **M** salidas para resolver un problema de su propía creación.

Se evaluara la correcta implementación de la red neuronal y la explicación de los elementos de la teoría vistos en clase.

####1. Plantear un problema a resolver con una red neuronal de una capa de entrada y una capa de salida. Las salidas no deben ser excluyentes, es decir, pueden pertenecer a mas de una clase. Algunos ejemplos son: A partir de caracteristicas de una vivienda, determinar si la vivienda es de algun estilo (moderna, agradable, tradicional). Pueden generar ustedes un pequeño dataset para utilizar o buscar en Kaggle.

Nuestra problematica se basa en predecir que avanzado elegirá el alumno basandonos en sus notas en los básicos y sus avanzados del año anterior.

In [2]:
import pandas as pd
data: pd.DataFrame = pd.read_csv('avanzados - Hoja 1.csv')
data

Nota arte  Nota base de datos  Nota IOT  Nota modelado 3D  Nota UX-UI  \
0         10                   9         8                 9           8   
1          9                   2         8                10          10   
2         10                   3         9                 7           9   
3          7                   8        10                 8           7   
4          9                   6         5                 8           7   
5          8                  10         9                 9          10   
6          4                   7         6                 9           8   
7          9                   9        10                 8           9   

   Nota tecnologías de la programación  Siguió TIMI?  Siguió redes?  \
0                                   10             1              0   
1                                    7             0              0   
2                                    8             1              1   
3                                    7             0              1   
4                                    8             1              0   
5                                   10             1              0   
6                                    7             1              0   
7                                    8             0              1   

   Siguió hardware?  Siguió programación?  Siguió videojuegos?  arte  \
0                 0                     1                    0     0   
1                 1                     0                    1     0   
2                 0                     0                    0     1   
3                 1                     0                    0     0   
4                 0                     0                    1     1   
5                 0                     0                    1     1   
6                 0                     1                    0     0   
7                 1                     0                    0     0   

   base de datos  IOT  ranzo  IA  videojuegos  
0              1    0      0   1            0  
1              0    1      1   0            0  
2              0    0      1   0            0  
3              1    1      0   0            0  
4              0    0      0   0            1  
5              0    0      0   1            0  
6              0    0      1   0            1  
7              1    1      0   0            0

In [3]:
training_inputs = data.drop(['arte', 'base de datos', 'IOT', 'ranzo', 'IA', 'videojuegos'], axis=1)
training_inputs

Nota arte  Nota base de datos  Nota IOT  Nota modelado 3D  Nota UX-UI  \
0         10                   9         8                 9           8   
1          9                   2         8                10          10   
2         10                   3         9                 7           9   
3          7                   8        10                 8           7   
4          9                   6         5                 8           7   
5          8                  10         9                 9          10   
6          4                   7         6                 9           8   
7          9                   9        10                 8           9   

   Nota tecnologías de la programación  Siguió TIMI?  Siguió redes?  \
0                                   10             1              0   
1                                    7             0              0   
2                                    8             1              1   
3                                    7             0              1   
4                                    8             1              0   
5                                   10             1              0   
6                                    7             1              0   
7                                    8             0              1   

   Siguió hardware?  Siguió programación?  Siguió videojuegos?  
0                 0                     1                    0  
1                 1                     0                    1  
2                 0                     0                    0  
3                 1                     0                    0  
4                 0                     0                    1  
5                 0                     0                    1  
6                 0                     1                    0  
7                 1                     0                    0

In [4]:
training_outputs = data[['arte', 'base de datos', 'IOT', 'ranzo', 'IA', 'videojuegos']]
training_outputs

arte  base de datos  IOT  ranzo  IA  videojuegos
0     0              1    0      0   1            0
1     0              0    1      1   0            0
2     1              0    0      1   0            0
3     0              1    1      0   0            0
4     1              0    0      0   0            1
5     1              0    0      0   1            0
6     0              0    0      1   0            1
7     0              1    1      0   0            0

In [5]:
import numpy as np
n = training_inputs.shape[1]
synaptic_weights = 2 + np.random.random((n,6)) - 1

display(synaptic_weights.shape)
synaptic_weights

(11, 6)

array([[1.93613968, 1.51768606, 1.00836401, 1.32175869, 1.42073247,
        1.1290158 ],
       [1.81005387, 1.86735694, 1.51207632, 1.50226575, 1.7037551 ,
        1.42446295],
       [1.05577519, 1.49943985, 1.41494602, 1.50260282, 1.29740661,
        1.05634896],
       [1.19740102, 1.49627098, 1.11555218, 1.57684291, 1.6633674 ,
        1.81351772],
       [1.40249411, 1.98375483, 1.13038805, 1.64406757, 1.29018766,
        1.62679264],
       [1.71256037, 1.36654589, 1.06599823, 1.34917526, 1.60329402,
        1.47308643],
       [1.61706706, 1.09006112, 1.50810852, 1.47617258, 1.53588193,
        1.63067306],
       [1.25766266, 1.41126475, 1.43504049, 1.82766885, 1.13516077,
        1.4589039 ],
       [1.00338727, 1.5543197 , 1.98276409, 1.73194529, 1.0247504 ,
        1.6898122 ],
       [1.77293635, 1.74813171, 1.75190363, 1.03007715, 1.63746112,
        1.09769278],
       [1.49204431, 1.71702493, 1.7285754 , 1.08417403, 1.25625503,
        1.78166486]])

In [6]:
def sigmoid(x):
    return 1 / ( 1 + np.exp(-x) )

def sigmoid_derivative(x):
    return x * (1 - x)

In [7]:
eval_NN = lambda x, w: sigmoid(np.dot(x, w))

In [8]:
# 50000 epochs
for iteration in range(50000):

    # Arranca con los valores de training
    input_layer = training_inputs

    # Genera un output haciendo la suma de los valores de input multiplicados por su peso sinaptico, y aplicandole la función sigmoide para normalizar a -1, 1
    outputs = eval_NN(input_layer, synaptic_weights)

    # Calculo el error
    error = training_outputs - outputs

    # Ajusto los pesos en funcion al error y al resultado obtenido
    adjustments = error * sigmoid_derivative(outputs)
    synaptic_weights += np.dot(input_layer.T, adjustments)

In [9]:
print('Synaptic weights after training')
print(synaptic_weights)

print('Outputs after training: ')
print(outputs)

Synaptic weights after training
[[1.93613968 1.51768606 1.00836401 1.32175869 1.42073247 1.1290158 ]
 [1.81005387 1.86735694 1.51207632 1.50226575 1.7037551  1.42446295]
 [1.05577519 1.49943985 1.41494602 1.50260282 1.29740661 1.05634896]
 [1.19740102 1.49627098 1.11555218 1.57684291 1.6633674  1.81351772]
 [1.40249411 1.98375483 1.13038805 1.64406757 1.29018766 1.62679264]
 [1.71256037 1.36654589 1.06599823 1.34917526 1.60329402 1.47308643]
 [1.61706706 1.09006112 1.50810852 1.47617258 1.53588193 1.63067306]
 [1.25766266 1.41126475 1.43504049 1.82766885 1.13516077 1.4589039 ]
 [1.00338727 1.5543197  1.98276409 1.73194529 1.0247504  1.6898122 ]
 [1.77293635 1.74813171 1.75190363 1.03007715 1.63746112 1.09769278]
 [1.49204431 1.71702493 1.7285754  1.08417403 1.25625503 1.78166486]]
Outputs after training: 
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [10]:
from IPython.display import HTML, display
large = lambda x : display(HTML('<p style="font-size: 50px; color: #66D148">'+str(x)+'</p>'))

In [11]:
Nota_arte = 10 #@param {type:"integer"}
Nota_base_de_datos = 9 #@param {type:"integer"}
Nota_IOT = 8 #@param {type:"integer"}
Nota_modelado = 7 #@param {type:"integer"}
Nota_UXUI = 6 #@param {type:"integer"}
Nota_tecnologias_de_la_programación = 10 #@param {type:"integer"}
Siguió_TIMI = 0 #@param {type:"integer"}
Siguió_redes = 0 #@param {type:"integer"}
Siguió_hardware = 0 #@param {type:"integer"}
Siguió_programación = 1 #@param {type:"integer"}
Siguió_videojuegos = 1 #@param {type:"integer"}

input_layer = np.array([Nota_arte, Nota_base_de_datos, Nota_IOT, Nota_modelado, Nota_UXUI, Nota_tecnologias_de_la_programación, Siguió_TIMI, Siguió_redes, Siguió_hardware, Siguió_programación, Siguió_videojuegos])
res = sigmoid(np.dot(input_layer, synaptic_weights))[0]
display(res)

thresh = 0.01
out = 0 if res < thresh else 1

large(out)

1.0

####2. Modificar la estructura de la red neuronal para que admita **N** neuronas de entrada y **M** neuronas de salida.

Nos dimos cuenta que para lograr que la red neuronal admita N neruronas de entrada y M neuronas de salida solo debemos modificar un bloque de codigo:

In [16]:
n = training_inputs.shape[1]
m = training_outputs.shape[1]
display(n, m)
synaptic_weights = 2 + np.random.random((n, m)) - 1
synaptic_weights

11

6

array([[1.45451618, 1.74031156, 1.9298298 , 1.91209435, 1.2103704 ,
        1.49622375],
       [1.60763692, 1.63381828, 1.49238144, 1.26271181, 1.82192629,
        1.19940128],
       [1.11021076, 1.1277508 , 1.70327982, 1.12345018, 1.98928798,
        1.37992199],
       [1.39754829, 1.9124875 , 1.43999728, 1.09868225, 1.49070532,
        1.16790468],
       [1.20454804, 1.96782466, 1.59860245, 1.76972979, 1.42272311,
        1.80029724],
       [1.6561395 , 1.60659056, 1.72228537, 1.59011978, 1.08432664,
        1.2640032 ],
       [1.80538568, 1.560068  , 1.07544414, 1.09566599, 1.74362215,
        1.65634824],
       [1.23294933, 1.89490221, 1.74808732, 1.84853725, 1.03782217,
        1.00448896],
       [1.51582444, 1.86869671, 1.42459265, 1.29191306, 1.41388773,
        1.26475857],
       [1.66666495, 1.32803439, 1.81828048, 1.85772018, 1.85274576,
        1.16630705],
       [1.87921636, 1.51824474, 1.11286081, 1.59762503, 1.68132326,
        1.91129004]])